@host = http://localhost:5295

GET  {{host}}/dinners
Authorization: : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMDVhZDgyZC02NTBhLTQwMTYtOWE2OS1mYTJmMDBjNmJjNWUiLCJnaXZlbl9uYW1lIjoiQ2hhcHB5IiwiZmFtaWx5X25hbWUiOiJNb2hhbW1lZCIsImp0aSI6IjUyOGU0OWFmLWE5MDYtNGQ2NS1hNmFjLWQzZGU0MjZlNTdhMSIsImV4cCI6MTY3MzI4MTgwMywiaXNzIjoiQW1pbkRpbm5lciIsImF1ZCI6IkFtaW5EaW5uZXIifQ.Bg1yODjuK4_Za7CQ3oJ5zh9Z0Vw_IRBBmegiHZ2wDM0
